extend type GameNight {
  """
  ✨ Implicit foreign key field based on `GameNight`.`creator`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  creatorId: String! @fdc_generated(from: "GameNight.creator", purpose: IMPLICIT_REF_FIELD)
}
extend type GameNightInvitation {
  """
  ✨ Implicit foreign key field based on `GameNightInvitation`.`gameNight`. It must match the value of `GameNight`.`id`. See `@ref` for how to customize it.
  """
  gameNightId: UUID! @fdc_generated(from: "GameNightInvitation.gameNight", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `GameNightInvitation`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "GameNightInvitation.user", purpose: IMPLICIT_REF_FIELD)
}
extend type GameNightProposal {
  """
  ✨ Implicit foreign key field based on `GameNightProposal`.`gameNight`. It must match the value of `GameNight`.`id`. See `@ref` for how to customize it.
  """
  gameNightId: UUID! @fdc_generated(from: "GameNightProposal.gameNight", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `GameNightProposal`.`suggestion`. It must match the value of `GameSuggestion`.`id`. See `@ref` for how to customize it.
  """
  suggestionId: UUID! @fdc_generated(from: "GameNightProposal.suggestion", purpose: IMPLICIT_REF_FIELD)
}
extend type GameSuggestion {
  """
  ✨ Implicit foreign key field based on `GameSuggestion`.`suggestedBy`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  suggestedById: String! @fdc_generated(from: "GameSuggestion.suggestedBy", purpose: IMPLICIT_REF_FIELD)
}
