"""
✨ `FoodItem_KeyOutput` returns the primary key fields of table type `FoodItem`.

It has the same format as `FoodItem_Key`, but is only used as mutation return value.
"""
scalar FoodItem_KeyOutput
"""
✨ `Game_KeyOutput` returns the primary key fields of table type `Game`.

It has the same format as `Game_Key`, but is only used as mutation return value.
"""
scalar Game_KeyOutput
"""
✨ `GameNight_KeyOutput` returns the primary key fields of table type `GameNight`.

It has the same format as `GameNight_Key`, but is only used as mutation return value.
"""
scalar GameNight_KeyOutput
"""
✨ `GameNightInvitation_KeyOutput` returns the primary key fields of table type `GameNightInvitation`.

It has the same format as `GameNightInvitation_Key`, but is only used as mutation return value.
"""
scalar GameNightInvitation_KeyOutput
"""
✨ `GameNightProposal_KeyOutput` returns the primary key fields of table type `GameNightProposal`.

It has the same format as `GameNightProposal_Key`, but is only used as mutation return value.
"""
scalar GameNightProposal_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ `Vote_KeyOutput` returns the primary key fields of table type `Vote`.

It has the same format as `Vote_Key`, but is only used as mutation return value.
"""
scalar Vote_KeyOutput
"""
✨ Generated data input type for table 'FoodItem'. It includes all necessary fields for creating or upserting rows into table.
"""
input FoodItem_Data {
  """
  ✨ Generated from Field `FoodItem`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `FoodItem`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `FoodItem`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `FoodItem`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `FoodItem`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `FoodItem`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'FoodItem'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input FoodItem_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [FoodItem_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: FoodItem_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [FoodItem_Filter!]
  """
  ✨ Generated from Field `FoodItem`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `FoodItem`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `FoodItem`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `FoodItem`.`gameNightProposals_on_foodItem` of type `[GameNightProposal!]!`
  """
  gameNightProposals_on_foodItem: GameNightProposal_ListFilter
}
"""
✨ Generated first-row input type for table 'FoodItem'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input FoodItem_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [FoodItem_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: FoodItem_Filter
}
"""
✨ Generated having input type for table 'FoodItem'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input FoodItem_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [FoodItem_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: FoodItem_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [FoodItem_Having!]
  """
  ✨ Generated from Field `FoodItem`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `FoodItem`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `FoodItem`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `FoodItem`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `FoodItem`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `FoodItem`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `FoodItem`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'FoodItem'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input FoodItem_Key {
  """
  ✨ Generated from Field `FoodItem`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `FoodItem`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'FoodItem'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input FoodItem_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: FoodItem_Filter
}
"""
✨ Generated order input type for table 'FoodItem'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input FoodItem_Order {
  """
  ✨ Generated from Field `FoodItem`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `FoodItem`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Game'. It includes all necessary fields for creating or upserting rows into table.
"""
input Game_Data {
  """
  ✨ Generated from Field `Game`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Game`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Game`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Game`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Game`.`maxPlayers` of type `Int`
  """
  maxPlayers: Int
  """
  ✨ `_expr` server value variant of `maxPlayers` (✨ Generated from Field `Game`.`maxPlayers` of type `Int`)
  """
  maxPlayers_expr: Int_Expr
  """
  ✨ `_update` server value variant of `maxPlayers` (✨ Generated from Field `Game`.`maxPlayers` of type `Int`)
  """
  maxPlayers_update: [Int_Update!]
  """
  ✨ Generated from Field `Game`.`minPlayers` of type `Int`
  """
  minPlayers: Int
  """
  ✨ `_expr` server value variant of `minPlayers` (✨ Generated from Field `Game`.`minPlayers` of type `Int`)
  """
  minPlayers_expr: Int_Expr
  """
  ✨ `_update` server value variant of `minPlayers` (✨ Generated from Field `Game`.`minPlayers` of type `Int`)
  """
  minPlayers_update: [Int_Update!]
  """
  ✨ Generated from Field `Game`.`title` of type `String!`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Game`.`title` of type `String!`)
  """
  title_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Game'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Game_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Game_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Game_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Game_Filter!]
  """
  ✨ Generated from Field `Game`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Game`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers` of type `Int`
  """
  maxPlayers: Int_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers` of type `Int`
  """
  minPlayers: Int_Filter
  """
  ✨ Generated from Field `Game`.`title` of type `String!`
  """
  title: String_Filter
  """
  ✨ Generated from Field `Game`.`gameNightProposals_on_game` of type `[GameNightProposal!]!`
  """
  gameNightProposals_on_game: GameNightProposal_ListFilter
}
"""
✨ Generated first-row input type for table 'Game'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Game_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Game_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Game_Filter
}
"""
✨ Generated having input type for table 'Game'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Game_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Game_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Game_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Game_Having!]
  """
  ✨ Generated from Field `Game`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Game`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers_count` of type `Int!`
  """
  maxPlayers_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers_count` of type `Int!`
  """
  minPlayers_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers_sum` of type `Int`
  """
  maxPlayers_sum: Int_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers_sum` of type `Int`
  """
  minPlayers_sum: Int_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers_avg` of type `Float`
  """
  maxPlayers_avg: Float_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers_avg` of type `Float`
  """
  minPlayers_avg: Float_Filter
  """
  ✨ Generated from Field `Game`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers_min` of type `Int`
  """
  maxPlayers_min: Int_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers_min` of type `Int`
  """
  minPlayers_min: Int_Filter
  """
  ✨ Generated from Field `Game`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Game`.`maxPlayers_max` of type `Int`
  """
  maxPlayers_max: Int_Filter
  """
  ✨ Generated from Field `Game`.`minPlayers_max` of type `Int`
  """
  minPlayers_max: Int_Filter
}
"""
✨ Generated key input type for table 'Game'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Game_Key {
  """
  ✨ Generated from Field `Game`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Game`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Game'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Game_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Game_Filter
}
"""
✨ Generated order input type for table 'Game'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Game_Order {
  """
  ✨ Generated from Field `Game`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Game`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Game`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers` of type `Int`
  """
  maxPlayers: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers` of type `Int`
  """
  minPlayers: OrderDirection
  """
  ✨ Generated from Field `Game`.`title` of type `String!`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Game`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Game`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers_count` of type `Int!`
  """
  maxPlayers_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers_count` of type `Int!`
  """
  minPlayers_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers_sum` of type `Int`
  """
  maxPlayers_sum: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers_sum` of type `Int`
  """
  minPlayers_sum: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers_avg` of type `Float`
  """
  maxPlayers_avg: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers_avg` of type `Float`
  """
  minPlayers_avg: OrderDirection
  """
  ✨ Generated from Field `Game`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers_min` of type `Int`
  """
  maxPlayers_min: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers_min` of type `Int`
  """
  minPlayers_min: OrderDirection
  """
  ✨ Generated from Field `Game`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Game`.`maxPlayers_max` of type `Int`
  """
  maxPlayers_max: OrderDirection
  """
  ✨ Generated from Field `Game`.`minPlayers_max` of type `Int`
  """
  minPlayers_max: OrderDirection
}
"""
✨ Generated data input type for table 'GameNight'. It includes all necessary fields for creating or upserting rows into table.
"""
input GameNight_Data {
  """
  ✨ Generated from Field `GameNight`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `GameNight`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNight`.`creatorId` of type `UUID!`
  """
  creatorId: UUID
  """
  ✨ `_expr` server value variant of `creatorId` (✨ Generated from Field `GameNight`.`creatorId` of type `UUID!`)
  """
  creatorId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNight`.`creator` of type `User!`
  """
  creator: User_Key
  """
  ✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `GameNight`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `GameNight`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `GameNight`.`eventDate` of type `Date!`
  """
  eventDate: Date
  """
  ✨ `_date` server value variant of `eventDate` (✨ Generated from Field `GameNight`.`eventDate` of type `Date!`)
  """
  eventDate_date: Date_Relative
  """
  ✨ `_expr` server value variant of `eventDate` (✨ Generated from Field `GameNight`.`eventDate` of type `Date!`)
  """
  eventDate_expr: Date_Expr
  """
  ✨ `_update` server value variant of `eventDate` (✨ Generated from Field `GameNight`.`eventDate` of type `Date!`)
  """
  eventDate_update: [Date_Update!]
  """
  ✨ Generated from Field `GameNight`.`eventTime` of type `String`
  """
  eventTime: String
  """
  ✨ `_expr` server value variant of `eventTime` (✨ Generated from Field `GameNight`.`eventTime` of type `String`)
  """
  eventTime_expr: String_Expr
  """
  ✨ Generated from Field `GameNight`.`isFinalized` of type `Boolean`
  """
  isFinalized: Boolean
  """
  ✨ `_expr` server value variant of `isFinalized` (✨ Generated from Field `GameNight`.`isFinalized` of type `Boolean`)
  """
  isFinalized_expr: Boolean_Expr
  """
  ✨ Generated from Field `GameNight`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `GameNight`.`name` of type `String!`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'GameNight'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNight_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [GameNight_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: GameNight_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [GameNight_Filter!]
  """
  ✨ Generated from Field `GameNight`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `GameNight`.`creatorId` of type `UUID!`
  """
  creatorId: UUID_Filter
  """
  ✨ Generated from Field `GameNight`.`creator` of type `User!`
  """
  creator: User_Filter
  """
  ✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `GameNight`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `GameNight`.`eventDate` of type `Date!`
  """
  eventDate: Date_Filter
  """
  ✨ Generated from Field `GameNight`.`eventTime` of type `String`
  """
  eventTime: String_Filter
  """
  ✨ Generated from Field `GameNight`.`isFinalized` of type `Boolean`
  """
  isFinalized: Boolean_Filter
  """
  ✨ Generated from Field `GameNight`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `GameNight`.`gameNightInvitations_on_gameNight` of type `[GameNightInvitation!]!`
  """
  gameNightInvitations_on_gameNight: GameNightInvitation_ListFilter
  """
  ✨ Generated from Field `GameNight`.`gameNightProposals_on_gameNight` of type `[GameNightProposal!]!`
  """
  gameNightProposals_on_gameNight: GameNightProposal_ListFilter
  """
  ✨ Generated from Field `GameNight`.`users_via_GameNightInvitation` of type `[User!]!`
  """
  users_via_GameNightInvitation: User_ListFilter
}
"""
✨ Generated first-row input type for table 'GameNight'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input GameNight_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [GameNight_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: GameNight_Filter
}
"""
✨ Generated having input type for table 'GameNight'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNight_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [GameNight_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: GameNight_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [GameNight_Having!]
  """
  ✨ Generated from Field `GameNight`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`creatorId_count` of type `Int!`
  """
  creatorId_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`eventDate_count` of type `Int!`
  """
  eventDate_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`eventTime_count` of type `Int!`
  """
  eventTime_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`isFinalized_count` of type `Int!`
  """
  isFinalized_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `GameNight`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `GameNight`.`eventDate_min` of type `Date`
  """
  eventDate_min: Date_Filter
  """
  ✨ Generated from Field `GameNight`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `GameNight`.`eventDate_max` of type `Date`
  """
  eventDate_max: Date_Filter
}
"""
✨ Generated key input type for table 'GameNight'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input GameNight_Key {
  """
  ✨ Generated from Field `GameNight`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `GameNight`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'GameNight'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input GameNight_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: GameNight_Filter
}
"""
✨ Generated order input type for table 'GameNight'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input GameNight_Order {
  """
  ✨ Generated from Field `GameNight`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`creatorId` of type `UUID!`
  """
  creatorId: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`creator` of type `User!`
  """
  creator: User_Order
  """
  ✨ Generated from Field `GameNight`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventDate` of type `Date!`
  """
  eventDate: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventTime` of type `String`
  """
  eventTime: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`isFinalized` of type `Boolean`
  """
  isFinalized: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`creatorId_count` of type `Int!`
  """
  creatorId_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventDate_count` of type `Int!`
  """
  eventDate_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventTime_count` of type `Int!`
  """
  eventTime_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`isFinalized_count` of type `Int!`
  """
  isFinalized_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventDate_min` of type `Date`
  """
  eventDate_min: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `GameNight`.`eventDate_max` of type `Date`
  """
  eventDate_max: OrderDirection
}
"""
✨ Generated data input type for table 'GameNightInvitation'. It includes all necessary fields for creating or upserting rows into table.
"""
input GameNightInvitation_Data {
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`
  """
  gameNightId: UUID
  """
  ✨ `_expr` server value variant of `gameNightId` (✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`)
  """
  gameNightId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`
  """
  inviteeId: UUID
  """
  ✨ `_expr` server value variant of `inviteeId` (✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`)
  """
  inviteeId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Key
  """
  ✨ Generated from Field `GameNightInvitation`.`invitee` of type `User!`
  """
  invitee: User_Key
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `GameNightInvitation`.`status` of type `String`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `GameNightInvitation`.`status` of type `String`)
  """
  status_expr: String_Expr
}
"""
✨ Generated filter input type for table 'GameNightInvitation'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNightInvitation_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [GameNightInvitation_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: GameNightInvitation_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [GameNightInvitation_Filter!]
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`
  """
  gameNightId: UUID_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`
  """
  inviteeId: UUID_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`invitee` of type `User!`
  """
  invitee: User_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`status` of type `String`
  """
  status: String_Filter
}
"""
✨ Generated first-row input type for table 'GameNightInvitation'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input GameNightInvitation_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [GameNightInvitation_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: GameNightInvitation_Filter
}
"""
✨ Generated having input type for table 'GameNightInvitation'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNightInvitation_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [GameNightInvitation_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: GameNightInvitation_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [GameNightInvitation_Having!]
  """
  ✨ Generated from Field `GameNightInvitation`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId_count` of type `Int!`
  """
  gameNightId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId_count` of type `Int!`
  """
  inviteeId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'GameNightInvitation'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input GameNightInvitation_Key {
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`
  """
  gameNightId: UUID
  """
  ✨ `_expr` server value variant of `gameNightId` (✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`)
  """
  gameNightId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`
  """
  inviteeId: UUID
  """
  ✨ `_expr` server value variant of `inviteeId` (✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`)
  """
  inviteeId_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'GameNightInvitation'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input GameNightInvitation_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: GameNightInvitation_Filter
}
"""
✨ Generated order input type for table 'GameNightInvitation'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input GameNightInvitation_Order {
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId` of type `UUID!`
  """
  gameNightId: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId` of type `UUID!`
  """
  inviteeId: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Order
  """
  ✨ Generated from Field `GameNightInvitation`.`invitee` of type `User!`
  """
  invitee: User_Order
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`status` of type `String`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`gameNightId_count` of type `Int!`
  """
  gameNightId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`inviteeId_count` of type `Int!`
  """
  inviteeId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `GameNightInvitation`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'GameNightProposal'. It includes all necessary fields for creating or upserting rows into table.
"""
input GameNightProposal_Data {
  """
  ✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightProposal`.`foodItemId` of type `UUID`
  """
  foodItemId: UUID
  """
  ✨ `_expr` server value variant of `foodItemId` (✨ Generated from Field `GameNightProposal`.`foodItemId` of type `UUID`)
  """
  foodItemId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightProposal`.`gameId` of type `UUID`
  """
  gameId: UUID
  """
  ✨ `_expr` server value variant of `gameId` (✨ Generated from Field `GameNightProposal`.`gameId` of type `UUID`)
  """
  gameId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightProposal`.`gameNightId` of type `UUID!`
  """
  gameNightId: UUID
  """
  ✨ `_expr` server value variant of `gameNightId` (✨ Generated from Field `GameNightProposal`.`gameNightId` of type `UUID!`)
  """
  gameNightId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightProposal`.`proposerId` of type `UUID!`
  """
  proposerId: UUID
  """
  ✨ `_expr` server value variant of `proposerId` (✨ Generated from Field `GameNightProposal`.`proposerId` of type `UUID!`)
  """
  proposerId_expr: UUID_Expr
  """
  ✨ Generated from Field `GameNightProposal`.`foodItem` of type `FoodItem`
  """
  foodItem: FoodItem_Key
  """
  ✨ Generated from Field `GameNightProposal`.`game` of type `Game`
  """
  game: Game_Key
  """
  ✨ Generated from Field `GameNightProposal`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Key
  """
  ✨ Generated from Field `GameNightProposal`.`proposer` of type `User!`
  """
  proposer: User_Key
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `GameNightProposal`.`type` of type `String!`
  """
  type: String
  """
  ✨ `_expr` server value variant of `type` (✨ Generated from Field `GameNightProposal`.`type` of type `String!`)
  """
  type_expr: String_Expr
}
"""
✨ Generated filter input type for table 'GameNightProposal'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNightProposal_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [GameNightProposal_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: GameNightProposal_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [GameNightProposal_Filter!]
  """
  ✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`foodItemId` of type `UUID`
  """
  foodItemId: UUID_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`gameId` of type `UUID`
  """
  gameId: UUID_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`gameNightId` of type `UUID!`
  """
  gameNightId: UUID_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`proposerId` of type `UUID!`
  """
  proposerId: UUID_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`foodItem` of type `FoodItem`
  """
  foodItem: FoodItem_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`game` of type `Game`
  """
  game: Game_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`proposer` of type `User!`
  """
  proposer: User_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`type` of type `String!`
  """
  type: String_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`votes_on_gameNightProposal` of type `[Vote!]!`
  """
  votes_on_gameNightProposal: Vote_ListFilter
}
"""
✨ Generated first-row input type for table 'GameNightProposal'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input GameNightProposal_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [GameNightProposal_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: GameNightProposal_Filter
}
"""
✨ Generated having input type for table 'GameNightProposal'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input GameNightProposal_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [GameNightProposal_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: GameNightProposal_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [GameNightProposal_Having!]
  """
  ✨ Generated from Field `GameNightProposal`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`foodItemId_count` of type `Int!`
  """
  foodItemId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`gameId_count` of type `Int!`
  """
  gameId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`gameNightId_count` of type `Int!`
  """
  gameNightId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`proposerId_count` of type `Int!`
  """
  proposerId_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`type_count` of type `Int!`
  """
  type_count: Int_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'GameNightProposal'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input GameNightProposal_Key {
  """
  ✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'GameNightProposal'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input GameNightProposal_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: GameNightProposal_Filter
}
"""
✨ Generated order input type for table 'GameNightProposal'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input GameNightProposal_Order {
  """
  ✨ Generated from Field `GameNightProposal`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`foodItemId` of type `UUID`
  """
  foodItemId: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`gameId` of type `UUID`
  """
  gameId: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`gameNightId` of type `UUID!`
  """
  gameNightId: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`proposerId` of type `UUID!`
  """
  proposerId: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`foodItem` of type `FoodItem`
  """
  foodItem: FoodItem_Order
  """
  ✨ Generated from Field `GameNightProposal`.`game` of type `Game`
  """
  game: Game_Order
  """
  ✨ Generated from Field `GameNightProposal`.`gameNight` of type `GameNight!`
  """
  gameNight: GameNight_Order
  """
  ✨ Generated from Field `GameNightProposal`.`proposer` of type `User!`
  """
  proposer: User_Order
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`type` of type `String!`
  """
  type: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`foodItemId_count` of type `Int!`
  """
  foodItemId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`gameId_count` of type `Int!`
  """
  gameId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`gameNightId_count` of type `Int!`
  """
  gameNightId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`proposerId_count` of type `Int!`
  """
  proposerId_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`type_count` of type `Int!`
  """
  type_count: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `GameNightProposal`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String!`)
  """
  displayName_expr: String_Expr
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String`)
  """
  email_expr: String_Expr
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`gameNights_on_creator` of type `[GameNight!]!`
  """
  gameNights_on_creator: GameNight_ListFilter
  """
  ✨ Generated from Field `User`.`gameNightInvitations_on_invitee` of type `[GameNightInvitation!]!`
  """
  gameNightInvitations_on_invitee: GameNightInvitation_ListFilter
  """
  ✨ Generated from Field `User`.`gameNightProposals_on_proposer` of type `[GameNightProposal!]!`
  """
  gameNightProposals_on_proposer: GameNightProposal_ListFilter
  """
  ✨ Generated from Field `User`.`votes_on_user` of type `[Vote!]!`
  """
  votes_on_user: Vote_ListFilter
  """
  ✨ Generated from Field `User`.`gameNights_via_GameNightInvitation` of type `[GameNight!]!`
  """
  gameNights_via_GameNightInvitation: GameNight_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Vote'. It includes all necessary fields for creating or upserting rows into table.
"""
input Vote_Data {
  """
  ✨ Generated from Field `Vote`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Vote`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Vote`.`gameNightProposalId` of type `UUID!`
  """
  gameNightProposalId: UUID
  """
  ✨ `_expr` server value variant of `gameNightProposalId` (✨ Generated from Field `Vote`.`gameNightProposalId` of type `UUID!`)
  """
  gameNightProposalId_expr: UUID_Expr
  """
  ✨ Generated from Field `Vote`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Vote`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr
  """
  ✨ Generated from Field `Vote`.`gameNightProposal` of type `GameNightProposal!`
  """
  gameNightProposal: GameNightProposal_Key
  """
  ✨ Generated from Field `Vote`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Vote'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Vote_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Vote_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Vote_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Vote_Filter!]
  """
  ✨ Generated from Field `Vote`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Vote`.`gameNightProposalId` of type `UUID!`
  """
  gameNightProposalId: UUID_Filter
  """
  ✨ Generated from Field `Vote`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Vote`.`gameNightProposal` of type `GameNightProposal!`
  """
  gameNightProposal: GameNightProposal_Filter
  """
  ✨ Generated from Field `Vote`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Vote'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Vote_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Vote_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Vote_Filter
}
"""
✨ Generated having input type for table 'Vote'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Vote_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Vote_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Vote_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Vote_Having!]
  """
  ✨ Generated from Field `Vote`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Vote`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Vote`.`gameNightProposalId_count` of type `Int!`
  """
  gameNightProposalId_count: Int_Filter
  """
  ✨ Generated from Field `Vote`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Vote`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Vote`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Vote`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Vote'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Vote_Key {
  """
  ✨ Generated from Field `Vote`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Vote`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Vote'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Vote_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Vote_Filter
}
"""
✨ Generated order input type for table 'Vote'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Vote_Order {
  """
  ✨ Generated from Field `Vote`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Vote`.`gameNightProposalId` of type `UUID!`
  """
  gameNightProposalId: OrderDirection
  """
  ✨ Generated from Field `Vote`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Vote`.`gameNightProposal` of type `GameNightProposal!`
  """
  gameNightProposal: GameNightProposal_Order
  """
  ✨ Generated from Field `Vote`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Vote`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Vote`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Vote`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Vote`.`gameNightProposalId_count` of type `Int!`
  """
  gameNightProposalId_count: OrderDirection
  """
  ✨ Generated from Field `Vote`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Vote`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Vote`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Vote`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
