extend type Query {
  """
  ✨ Look up a single `GameNight` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gameNight(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameNight_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameNight_FirstRow
  ): GameNight @fdc_generated(from: "GameNight", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GameNightInvitation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gameNightInvitation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameNightInvitation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameNightInvitation_FirstRow
  ): GameNightInvitation @fdc_generated(from: "GameNightInvitation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GameNightProposal` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gameNightProposal(
    """
    The key used to identify the object.
    """
    key: GameNightProposal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameNightProposal_FirstRow
  ): GameNightProposal @fdc_generated(from: "GameNightProposal", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GameSuggestion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gameSuggestion(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameSuggestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameSuggestion_FirstRow
  ): GameSuggestion @fdc_generated(from: "GameSuggestion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `GameNight` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gameNights(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNight_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNight_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNight_Having
  ): [GameNight!]! @fdc_generated(from: "GameNight", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GameNightInvitation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gameNightInvitations(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightInvitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightInvitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightInvitation_Having
  ): [GameNightInvitation!]! @fdc_generated(from: "GameNightInvitation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GameNightProposal` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gameNightProposals(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightProposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightProposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightProposal_Having
  ): [GameNightProposal!]! @fdc_generated(from: "GameNightProposal", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GameSuggestion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gameSuggestions(
    """
    Filter condition to narrow down the query results.
    """
    where: GameSuggestion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameSuggestion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameSuggestion_Having
  ): [GameSuggestion!]! @fdc_generated(from: "GameSuggestion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
