extend type GameNight {
  """
  ✨ List `GameNightInvitation` objects in a one-to-many relationship (where `GameNightInvitation`.`gameNight` is this object).
  """
  gameNightInvitations_on_gameNight(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightInvitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightInvitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightInvitation_Having
  ): [GameNightInvitation!]! @fdc_generated(from: "GameNightInvitation.gameNight", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `GameNightProposal` objects in a one-to-many relationship (where `GameNightProposal`.`gameNight` is this object).
  """
  gameNightProposals_on_gameNight(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightProposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightProposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightProposal_Having
  ): [GameNightProposal!]! @fdc_generated(from: "GameNightProposal.gameNight", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `GameSuggestion` objects using `GameNightProposal` as the join table (a `GameNightProposal` object exists where its `gameNight` is this and its `suggestion` is that).
  """
  gameSuggestions_via_GameNightProposal(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightProposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightProposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightProposal_Having
  ): [GameSuggestion!]! @fdc_generated(from: "GameNightProposal", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "GameNight", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `GameNight` table.
  """
  _count: Int! @fdc_generated(from: "GameNight.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `creatorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  creatorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.creatorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `eventDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  eventDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.eventDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `eventTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  eventTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.eventTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `isFinalized` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isFinalized_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.isFinalized", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNight` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNight.name", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `GameNight` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "GameNight.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `eventDate` field in the `GameNight` table.
  """
  eventDate_min: Date @fdc_generated(from: "GameNight.eventDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `GameNight` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "GameNight.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `eventDate` field in the `GameNight` table.
  """
  eventDate_max: Date @fdc_generated(from: "GameNight.eventDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "GameNight.id", purpose: GLOBAL_ID)
}
extend type GameNightInvitation {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "GameNightInvitation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table.
  """
  _count: Int! @fdc_generated(from: "GameNightInvitation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightInvitation.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table where the `gameNightId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  gameNightId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightInvitation.gameNightId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightInvitation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightInvitation.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightInvitation` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightInvitation.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `GameNightInvitation` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "GameNightInvitation.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `GameNightInvitation` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "GameNightInvitation.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "GameNightInvitation.id", purpose: GLOBAL_ID)
}
extend type GameNightProposal {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "GameNightProposal", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `GameNightProposal` table.
  """
  _count: Int! @fdc_generated(from: "GameNightProposal.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightProposal` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightProposal.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightProposal` table where the `gameNightId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  gameNightId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightProposal.gameNightId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameNightProposal` table where the `suggestionId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  suggestionId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameNightProposal.suggestionId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `GameNightProposal` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "GameNightProposal.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `GameNightProposal` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "GameNightProposal.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "GameNightProposal.gameNightId,suggestionId", purpose: GLOBAL_ID)
}
extend type GameSuggestion {
  """
  ✨ List `GameNightProposal` objects in a one-to-many relationship (where `GameNightProposal`.`suggestion` is this object).
  """
  gameNightProposals_on_suggestion(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightProposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightProposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightProposal_Having
  ): [GameNightProposal!]! @fdc_generated(from: "GameNightProposal.suggestion", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `GameNight` objects using `GameNightProposal` as the join table (a `GameNightProposal` object exists where its `suggestion` is this and its `gameNight` is that).
  """
  gameNights_via_GameNightProposal(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightProposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightProposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightProposal_Having
  ): [GameNight!]! @fdc_generated(from: "GameNightProposal", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "GameSuggestion", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `GameSuggestion` table.
  """
  _count: Int! @fdc_generated(from: "GameSuggestion.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameSuggestion` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameSuggestion.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameSuggestion` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameSuggestion.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameSuggestion` table where the `suggestedById` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  suggestedById_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameSuggestion.suggestedById", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameSuggestion` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameSuggestion.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `GameSuggestion` table where the `votes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  votes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "GameSuggestion.votes", purpose: QUERY_COUNT)
  """
  ✨ Sum the `votes` field in the `GameSuggestion` table.
  """
  votes_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "GameSuggestion.votes", purpose: QUERY_SUM)
  """
  ✨ Average the `votes` field in the `GameSuggestion` table.
  """
  votes_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "GameSuggestion.votes", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `GameSuggestion` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "GameSuggestion.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `votes` field in the `GameSuggestion` table.
  """
  votes_min: Int @fdc_generated(from: "GameSuggestion.votes", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `GameSuggestion` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "GameSuggestion.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `votes` field in the `GameSuggestion` table.
  """
  votes_max: Int @fdc_generated(from: "GameSuggestion.votes", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "GameSuggestion.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `GameNight` objects in a one-to-many relationship (where `GameNight`.`creator` is this object).
  """
  gameNights_on_creator(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNight_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNight_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNight_Having
  ): [GameNight!]! @fdc_generated(from: "GameNight.creator", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `GameNightInvitation` objects in a one-to-many relationship (where `GameNightInvitation`.`user` is this object).
  """
  gameNightInvitations_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: GameNightInvitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameNightInvitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameNightInvitation_Having
  ): [GameNightInvitation!]! @fdc_generated(from: "GameNightInvitation.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `GameSuggestion` objects in a one-to-many relationship (where `GameSuggestion`.`suggestedBy` is this object).
  """
  gameSuggestions_on_suggestedBy(
    """
    Filter condition to narrow down the query results.
    """
    where: GameSuggestion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameSuggestion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameSuggestion_Having
  ): [GameSuggestion!]! @fdc_generated(from: "GameSuggestion.suggestedBy", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
